# Lighter Hedge Trading System Configuration
# 支持自动获取账户index的配置示例

# Global settings
global:
  api_url: "https://mainnet.zklighter.elliot.ai"
  ws_url: "wss://mainnet.zklighter.elliot.ai/stream"
  log_level: "INFO"
  monitoring_interval: 5  # seconds
  enable_auto_trading: true
  enable_real_time_trigger: true
  max_concurrent_trades: 10
  auto_reconnect: true
  max_reconnect_attempts: 5

# Web interface settings
web:
  port: 3000
  enable_web_interface: true
  cors_origins: ["*"]

# Risk management
risk_management:
  global_max_daily_loss: 5000
  global_max_position_size: 50000
  global_max_slippage: 0.02
  emergency_stop_enabled: true
  risk_check_interval: 10  # seconds

# Price triggering configuration
price_triggering:
  enable_websocket: true
  fallback_to_polling: true
  polling_interval: 2  # seconds
  price_change_threshold: 0.001  # 0.1%
  default_max_spread_percent: 0.01  # 1%
  default_max_volatility_percent: 0.20  # 20%

# Trading engine settings
trading_engine:
  enable_simultaneous_execution: true
  order_timeout: 30  # seconds
  position_check_interval: 5  # seconds
  max_retry_attempts: 3
  cooldown_between_retries: 1  # seconds

# Accounts configuration with auto-index feature
accounts:
  # 示例1: 使用自动获取index功能
  - index: 0  # 设置为0，系统将自动通过l1_address获取正确的index
    l1_address: "0xCaAE13268a82873C25250e4429B00a74504cc4D6"
    private_key: "your_private_key_here"
    api_key_index: 111
    is_active: true
    max_daily_trades: 100
    risk_limits:
      max_daily_loss: 1000
      max_position_size: 10000
      max_slippage: 0.05
      min_balance: 0

  # 示例2: 使用自动获取index功能
  - index: 0  # 设置为0，系统将自动通过l1_address获取正确的index
    l1_address: "0x0B9F983cFAB56a5D95d8DC3b486b7909683169cc"
    private_key: "your_private_key_here"
    api_key_index: 222
    is_active: true
    max_daily_trades: 100
    risk_limits:
      max_daily_loss: 1000
      max_position_size: 10000
      max_slippage: 0.05
      min_balance: 0

  # 示例3: 手动指定index（如果您已知正确的index）
  - index: 165652  # 手动指定已知的正确index
    l1_address: "0xYourWalletAddress"
    private_key: "your_private_key_here"
    api_key_index: 333
    is_active: true
    max_daily_trades: 100
    risk_limits:
      max_daily_loss: 1000
      max_position_size: 10000
      max_slippage: 0.05
      min_balance: 0

# Trading pairs configuration
trading_pairs:
  - id: "btc-hedge-1"
    name: "BTC 对冲组合 1"
    market_index: 1
    is_enabled: true
    stop_take_distance: 0.3  # 0.3%距离
    leverage: 20
    max_positions: 3
    cooldown_minutes: 2
    account_addresses:
      - "0xCaAE13268a82873C25250e4429B00a74504cc4D6"  # 系统会自动获取这些地址的正确index
      - "0x0B9F983cFAB56a5D95d8DC3b486b7909683169cc"  # 系统会自动获取这些地址的正确index
    hedge_strategy: "balanced"
    risk_limits:
      max_daily_loss: 500
      max_position_size: 5000
      max_slippage: 0.005
      min_balance: 0
    price_conditions:
      max_spread_percent: 0.01      # 1%
      max_volatility_percent: 0.10  # 10%
      min_liquidity_depth: 0.2    # 0.2 BTC深度即可